// <auto-generated />
namespace BookingApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class migrv1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migrv1));
        
        string IMigrationMetadata.Id
        {
            get { return "201706111353598_migrv1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
