//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomReservations
    {
        public int Id { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.TimeSpan Timestamp { get; set; }
    
        public virtual User User { get; set; }
        public virtual Room Room { get; set; }
    }
}
